server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3316/orderdb?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: order_user
    password: order_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123

  web:
    resources:
      cache:
        period: 0

  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: never

services:
  inventory:
    url: ${INVENTORY_SERVICE_URL:http://localhost:8081}